parameter_defaults:
  
  NovaReservedHostMemory: 1024
  
  ControllerCount: 1
  OvercloudControllerFlavor: control
  
  R220ComputeCount: 4
  OvercloudComputeFlavor: R220Compute

  R630ComputeCount: 2
  OvercloudComputeFlavor: R630Compute

  CephStorageCount: 5
  OvercloudCephStorageFlavor: ceph-storage

  ControllerSchedulerHints:
    'capabilities:node': 'controller-%index%'
  CephStorageSchedulerHints:
    'capabilities:node': 'cephstorage-%index%'
  R630ComputeSchedulerHints:
    'capabilities:node': 'compute-r630-%index%'
  R220ComputeSchedulerHints:
    'capabilities:node': 'compute-r220-%index%'
  
  HostnameMap:
    overcloud-controller-0: controller-0

    overcloud-R630compute-0: compute-r630-0
    overcloud-R630compute-1: compute-r630-1

    overcloud-R220compute-0: compute-r220-0
    overcloud-R220compute-1: compute-r220-1
    overcloud-R220compute-2: compute-r220-2
    overcloud-R220compute-3: compute-r220-3

    overcloud-cephstorage-0: cephstorage-0
    overcloud-cephstorage-1: cephstorage-1
    overcloud-cephstorage-2: cephstorage-2
    overcloud-cephstorage-3: cephstorage-3
    overcloud-cephstorage-4: cephstorage-4

  # Misc Config
  NtpServer: 'pool.ntp.org'
  NeutronNetworkType: 'vxlan,vlan'
  NeutronTunnelTypes: 'vxlan'

  ControllerIPs:
    # Each controller will get an IP from the lists below, first controller, first IP
    internal_api:
    - 172.17.1.201
    tenant:
    - 172.17.2.201    
    storage:
    - 172.17.3.201
    storage_mgmt:
    - 172.17.4.201
    external:
    - 192.168.122.201

  ComputeIPs:
    # Each compute will get an IP from the lists below, first compute, first IP
    internal_api:
    - 172.17.1.211
    - 172.17.1.212
    - 172.17.1.213
    - 172.17.1.214
    - 172.17.1.215
    - 172.17.1.216
    storage:
    - 172.17.3.211
    - 172.17.3.212
    - 172.17.3.213
    - 172.17.3.214
    - 172.17.3.215
    - 172.17.3.216                
    tenant:
    - 172.17.2.211
    - 172.17.2.212
    - 172.17.2.213
    - 172.17.2.214
    - 172.17.2.215
    - 172.17.2.216

  CephStorageIPs:
    # Each ceph node will get an IP from the lists below, first node, first IP
    storage:
    - 172.17.3.221
    - 172.17.3.222
    - 172.17.3.223
    - 172.17.3.224
    - 172.17.3.225
    storage_mgmt:
    - 172.17.4.221
    - 172.17.4.222
    - 172.17.4.223
    - 172.17.4.224
    - 172.17.4.225
