heat_template_version: 2016-10-14

description: This template will create flavors

resources:

  instance_flavor:
    type: OS::Nova::Flavor
    properties:
      is_public: true
      name: m1.small
      ram: 2048
      vcpus: 2
      disk: 20
